apiVersion: apps/v1
kind: Deployment
metadata:
  name: "java-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: "gcr.io/tech-rnd-project/java"
          ports:
            - containerPort: 8080
