---   
- hosts: My_Group
  vars:
    username: "admin"
    password: "admin"
  become: yes
  become_method: sudo


  tasks:

    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted 

    - name: Sleep for 30 seconds and continue with play
      wait_for: 
        timeout: 30
    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
       - /var/lib/jenkins/jobs/springboot
       - /var/lib/jenkins/jobs/springboot/build

    - name: Change permissions
      file:
        path: /var/lib/jenkins/jobs/springboot
        mode: '0777'
        recurse: yes
    - name: Make sure we have a 'jenkins' group
      group:
        name=jenkins
        state=present

    - name: Copy file from local to remote server
      copy:
        src: nextBuildNumber
        dest: /var/lib/jenkins/jobs/springboot/
        mode: '0777'



    - name: Copy file from local to remote server
      copy:
        src: config.xml
        dest: /var/lib/jenkins/jobs/springboot/
        mode: '0777'

    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted   